/**
 * HealthTrack — health-import MCP Server
 *
 * Simulates an external health data source (Apple Health / Garmin) and exposes
 * three tools that Kiro can call to import synthetic weight records into the
 * HealthTrack WeightEntry schema.
 *
 * Transport: stdio (JSON-RPC over stdin/stdout)
 * SDK:       @modelcontextprotocol/sdk v1.x  (McpServer high-level API)
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { z } from 'zod';

// ---------------------------------------------------------------------------
// Load synthetic dataset
// ---------------------------------------------------------------------------

const __filename = fileURLToPath(import.meta.url);
const __dir = dirname(__filename);
const DATA_PATH = join(__dir, '..', 'data', 'sample-health-data.json');

interface RawRecord {
  id: string;
  date: string;       // YYYY-MM-DD
  weightKg: number;
  source: string;
  notes: string | null;
}

interface DataFile {
  _meta: { note: string };
  profile: { heightCm: number; dateOfBirth: string };
  records: RawRecord[];
}

const dataset = JSON.parse(readFileSync(DATA_PATH, 'utf-8')) as DataFile;
const { records, profile } = dataset;

// ---------------------------------------------------------------------------
// BMI helpers (mirrors src/domain/bmi.ts — kept local to avoid coupling)
// ---------------------------------------------------------------------------

type BMICategory = 'underweight' | 'normal' | 'overweight' | 'obese';

function calculateBMI(weightKg: number, heightCm: number): { value: number; category: BMICategory } {
  const h = heightCm / 100;
  const raw = weightKg / (h * h);
  const value = Math.round(raw * 100) / 100;
  const category: BMICategory =
    value < 18.5 ? 'underweight' :
    value < 25.0 ? 'normal' :
    value < 30.0 ? 'overweight' : 'obese';
  return { value, category };
}

// ---------------------------------------------------------------------------
// WeightEntry shape (matches src/db/schema.ts)
// ---------------------------------------------------------------------------

interface WeightEntryPayload {
  /** UUID v4 — to be generated by the repository on insert */
  id: null;
  /** Should be FIXED_USER_ID on the receiving app */
  userId: null;
  date: string;
  weightKg: number;
  bmi: number;
  bmiCategory: BMICategory;
  /** Non-standard field kept for traceability; app can ignore it */
  sourceSystem: string;
}

function toWeightEntry(record: RawRecord): WeightEntryPayload {
  const { value, category } = calculateBMI(record.weightKg, profile.heightCm);
  return {
    id: null,
    userId: null,
    date: record.date,
    weightKg: record.weightKg,
    bmi: value,
    bmiCategory: category,
    sourceSystem: record.source,
  };
}

// ---------------------------------------------------------------------------
// MCP Server
// ---------------------------------------------------------------------------

const server = new McpServer({
  name: 'healthtrack-health-import',
  version: '1.0.0',
});

// ── Tool 1: list_sample_records ────────────────────────────────────────────

server.registerTool(
  'list_sample_records',
  {
    description:
      'Lists all synthetic weight records available in the sample dataset. ' +
      'Simulates what would come from Apple Health or Garmin Connect. ' +
      'NOTE: all data is fictitious and generated for demo purposes only.',
    inputSchema: z.object({}),
  },
  async () => {
    const summary = records.map((r) => {
      const { value, category } = calculateBMI(r.weightKg, profile.heightCm);
      return {
        id: r.id,
        date: r.date,
        weightKg: r.weightKg,
        bmi: value,
        bmiCategory: category,
        source: r.source,
      };
    });

    return {
      content: [
        {
          type: 'text' as const,
          text: JSON.stringify(
            {
              total: summary.length,
              profileHeightCm: profile.heightCm,
              records: summary,
            },
            null,
            2,
          ),
        },
      ],
    };
  },
);

// ── Tool 2: get_record_by_id ───────────────────────────────────────────────

server.registerTool(
  'get_record_by_id',
  {
    description: 'Returns the full detail of a single synthetic health record by its id.',
    inputSchema: z.object({
      id: z.string().describe('Record id, e.g. "ext-007"'),
    }),
  },
  async ({ id }) => {
    const record = records.find((r) => r.id === id);

    if (!record) {
      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify({ error: `Record "${id}" not found.` }),
          },
        ],
        isError: true,
      };
    }

    const { value, category } = calculateBMI(record.weightKg, profile.heightCm);

    return {
      content: [
        {
          type: 'text' as const,
          text: JSON.stringify(
            {
              ...record,
              bmi: value,
              bmiCategory: category,
              profileHeightCm: profile.heightCm,
            },
            null,
            2,
          ),
        },
      ],
    };
  },
);

// ── Tool 3: import_records_to_weight_tracking ──────────────────────────────

server.registerTool(
  'import_records_to_weight_tracking',
  {
    description:
      'Returns synthetic records mapped to the HealthTrack WeightEntry schema. ' +
      'Accepts either a date range (fromDate / toDate, inclusive, YYYY-MM-DD) ' +
      'or an explicit list of record ids. ' +
      'The returned payloads are ready to INSERT into the weight_entry table; ' +
      'id and userId are null — they must be filled by the repository before inserting.',
    inputSchema: z.object({
      fromDate: z
        .string()
        .regex(/^\d{4}-\d{2}-\d{2}$/)
        .optional()
        .describe('Start date (inclusive), YYYY-MM-DD'),
      toDate: z
        .string()
        .regex(/^\d{4}-\d{2}-\d{2}$/)
        .optional()
        .describe('End date (inclusive), YYYY-MM-DD'),
      ids: z
        .array(z.string())
        .optional()
        .describe('Explicit list of record ids to import'),
    }),
  },
  async ({ fromDate, toDate, ids }) => {
    let filtered: RawRecord[];

    if (ids && ids.length > 0) {
      filtered = records.filter((r) => ids.includes(r.id));
    } else if (fromDate || toDate) {
      filtered = records.filter((r) => {
        if (fromDate && r.date < fromDate) return false;
        if (toDate   && r.date > toDate)   return false;
        return true;
      });
    } else {
      // No filter → return all
      filtered = records;
    }

    if (filtered.length === 0) {
      return {
        content: [
          {
            type: 'text' as const,
            text: JSON.stringify({
              error: 'No records matched the given filter.',
              fromDate,
              toDate,
              ids,
            }),
          },
        ],
        isError: true,
      };
    }

    const payloads: WeightEntryPayload[] = filtered.map(toWeightEntry);

    return {
      content: [
        {
          type: 'text' as const,
          text: JSON.stringify(
            {
              count: payloads.length,
              note: '⚠️ SYNTHETIC DATA — not real health measurements. id and userId are null; fill them before inserting.',
              weightEntries: payloads,
            },
            null,
            2,
          ),
        },
      ],
    };
  },
);

// ---------------------------------------------------------------------------
// Start
// ---------------------------------------------------------------------------

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  // Log to stderr so it does not pollute the stdio JSON-RPC channel
  process.stderr.write('✅ health-import MCP server running via stdio\n');
}

main().catch((err) => {
  process.stderr.write(`❌ Server failed to start: ${err}\n`);
  process.exit(1);
});
